# Generated by Django 5.2.3 on 2025-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='resume',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
